spring.application.name=ticket.management.system

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/trainticketdb
spring.datasource.username=root
spring.datasource.password=আপনার_পাসওয়ার্ড
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Security (Development purpose)
spring.security.user.name=admin
spring.security.user.password=admin123

